version: "3.8"
services:
  redis-c-1:
    image: redis:5.0.14
    container_name: redis-c-1
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    volumes:
      - ./redis-c-1/data:/data
      - ./conf/cluster/redis-cluster-1.conf:/usr/local/etc/redis/redis.conf
    network_mode: host
  redis-c-2:
    image: redis:5.0.14
    container_name: redis-c-2
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    volumes:
      - ./redis-c-2/data:/data
      - ./conf/cluster/redis-cluster-2.conf:/usr/local/etc/redis/redis.conf
    network_mode: host
  redis-c-3:
    image: redis:5.0.14
    container_name: redis-c-3
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    volumes:
      - ./redis-c-3/data:/data
      - ./conf/cluster/redis-cluster-3.conf:/usr/local/etc/redis/redis.conf
    network_mode: host
  redis-c-4:
    image: redis:5.0.14
    container_name: redis-c-4
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    volumes:
      - ./redis-c-4/data:/data
      - ./conf/cluster/redis-cluster-4.conf:/usr/local/etc/redis/redis.conf
    network_mode: host
  redis-c-5:
    image: redis:5.0.14
    container_name: redis-c-5
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    volumes:
      - ./redis-c-5/data:/data
      - ./conf/cluster/redis-cluster-3.conf:/usr/local/etc/redis/redis.conf
    network_mode: host
  redis-c-6:
    image: redis:5.0.14
    container_name: redis-c-6
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    volumes:
      - ./redis-c-6/data:/data
      - ./conf/cluster/redis-cluster-3.conf:/usr/local/etc/redis/redis.conf
    network_mode: host