version: "3.8"
services:
  redis-s-1:
    image: redis:5.0.14
    container_name: redis-s-1
    command: redis-sentinel /usr/local/etc/redis/redis.conf
    restart: always
    volumes:
      - ./redis-s-1/data:/data
      - ./conf/sentinel/redis-sentinel-1.conf:/usr/local/etc/redis/redis.conf
    network_mode: host
  redis-s-2:
    image: redis:5.0.14
    container_name: redis-s-2
    command: redis-sentinel /usr/local/etc/redis/redis.conf
    restart: always
    volumes:
      - ./redis-s-2/data:/data
      - ./conf/sentinel/redis-sentinel-2.conf:/usr/local/etc/redis/redis.conf
    network_mode: host
  redis-s-3:
    image: redis:5.0.14
    container_name: redis-s-3
    command: redis-sentinel /usr/local/etc/redis/redis.conf
    restart: always
    volumes:
      - ./redis-s-3/data:/data
      - ./conf/sentinel/redis-sentinel-3.conf:/usr/local/etc/redis/redis.conf
    network_mode: host
  redis-s-4:
    image: redis:5.0.14
    container_name: redis-s-4
    command: redis-sentinel /usr/local/etc/redis/redis.conf
    restart: always
    volumes:
      - ./redis-s-4/data:/data
      - ./conf/sentinel/redis-sentinel-4.conf:/usr/local/etc/redis/redis.conf
    network_mode: host
  redis-s-5:
    image: redis:5.0.14
    container_name: redis-s-5
    command: redis-sentinel /usr/local/etc/redis/redis.conf
    restart: always
    volumes:
      - ./redis-s-5/data:/data
      - ./conf/sentinel/redis-sentinel-5.conf:/usr/local/etc/redis/redis.conf
    network_mode: host