server:
  port: 9003
spring:
  application:
    name: product
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.102.254
        namespace: dev
        group: dog
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.102.254:3306/dog
    username: root
    password: root
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/**/*Mapper.xml