server:
  port: 9003
spring:
  application:
    name: product
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.102.254
        namespace: dev
        group: dog
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.102.254:3306/dog
      username: root
      password: root
      initial-size: 10  # 初始连接数：连接池初始建立的连接数；
      min-idle: 20      # 最小连接数：连接池中保持的最小连接数；
      max-active: 30    # 最大连接数：连接池中最大允许的连接数；
      max-wait: 160     # 最大等待时间：获取连接的最大等待时间，超时将抛出异常(单位毫秒)
  data:
    redis:
      database: 0
#      host: 192.168.102.254
#      port: 6380
#      集群模式(只写主节点就可以)
      cluster:
        nodes: 192.168.102.254:6379,192.168.102.254:6380,192.168.102.254:6381
#      哨兵模式
#      sentinel:
#        master: mymaster
#        nodes: 192.168.102.254:26379,192.168.102.254:26380,192.168.102.254:26381,192.168.102.254:26382,192.168.102.254:26383
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/**/*Mapper.xml
feign:
  sentinel:
    enabled: true