server:
  port: 9003
spring:
  application:
    name: product
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.102.254
        namespace: dev
        group: dog
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.102.254:3306/dog
    username: root
    password: root
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
  data:
    redis:
      database: 0
#      host: 192.168.102.254
#      port: 6379
      cluster:
        nodes: 192.168.102.254:6379,192.168.102.254:6380,192.168.102.254:6381,192.168.102.254:6382,192.168.102.254:6383,192.168.102.254:6384
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/**/*Mapper.xml
feign:
  sentinel:
    enabled: true