server:
  port: 9002
spring:
  application:
    name: order
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.102.254
        namespace: dev
        group: dog
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.102.254:3306/dog
      username: root
      password: root
      initial-size: 10  # 初始连接数：连接池初始建立的连接数；
      min-idle: 20      # 最小连接数：连接池中保持的最小连接数；
      max-active: 30    # 最大连接数：连接池中最大允许的连接数；
      max-wait: 160     # 最大等待时间：获取连接的最大等待时间，超时将抛出异常(单位毫秒)
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/**/*Mapper.xml
feign:
  sentinel:
    enabled: true