version: "3.8"
services:
  mysql-5:
    image: mysql:5.7.44
    container_name: mysql-5
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root #设置root帐号密码
    ports:
      - 3306:3306
    volumes:
      - ./mysql/db-5:/var/lib/mysql #数据文件挂载
      - ./mysql/conf-5:/etc/mysql/conf.d #配置文件挂载
      - ./mysql/log-5:/var/log/mysql #日志文件挂载
    networks:
      - default
  nacos:
    image: nacos/nacos-server:v2.3.1
    container_name: nacos
    environment:
      - MODE=standalone
    volumes:
      - ./nacos/standalone-logs:/home/nacos/logs
    ports:
      - 8848:8848
      - 9848:9848
    networks:
      - default
  redis-c-1:
    image: redis:5.0.14
    container_name: redis-c-1
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    volumes:
      - ./redis/redis-c-1/data:/data
      - ./redis/conf/cluster/redis-cluster-1.conf:/usr/local/etc/redis/redis.conf
    network_mode: host
  redis-c-2:
    image: redis:5.0.14
    container_name: redis-c-2
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    volumes:
      - ./redis/redis-c-2/data:/data
      - ./redis/conf/cluster/redis-cluster-2.conf:/usr/local/etc/redis/redis.conf
    network_mode: host
  redis-c-3:
    image: redis:5.0.14
    container_name: redis-c-3
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    volumes:
      - ./redis/redis-c-3/data:/data
      - ./redis/conf/cluster/redis-cluster-3.conf:/usr/local/etc/redis/redis.conf
    network_mode: host
  redis-c-4:
    image: redis:5.0.14
    container_name: redis-c-4
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    volumes:
      - ./redis/redis-c-4/data:/data
      - ./redis/conf/cluster/redis-cluster-4.conf:/usr/local/etc/redis/redis.conf
    network_mode: host
  redis-c-5:
    image: redis:5.0.14
    container_name: redis-c-5
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    volumes:
      - ./redis/redis-c-5/data:/data
      - ./redis/conf/cluster/redis-cluster-5.conf:/usr/local/etc/redis/redis.conf
    network_mode: host
  redis-c-6:
    image: redis:5.0.14
    container_name: redis-c-6
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    volumes:
      - ./redis/redis-c-6/data:/data
      - ./redis/conf/cluster/redis-cluster-6.conf:/usr/local/etc/redis/redis.conf
    network_mode: host
#  sentinel:
#    image: bladex/sentinel-dashboard:1.8.7
#    container_name: sentinel
#    ports:
#      - 8858:8858
#      - 8719:8719
#    networks:
#      - default
networks:
  default:
    name: custom-bridge
    external: true